export const metadata = {
  title: "Terms of Service | Solomon's Logic",
  description: "Terms of Service for Solomon's Logic AI Receptionist service.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-950 text-gray-100 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold mb-2 text-white">Terms of Service</h1>
        <p className="text-gray-400 mb-10">Last updated: June 2, 2026</p>

        <section className="space-y-8 text-gray-300 leading-relaxed">
          <div>
            <h2 className="text-xl font-semibold text-white mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Solomon&apos;s Logic (&quot;the Service&quot;), you agree to be bound
              by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">2. Description of Service</h2>
            <p>
              Solomon&apos;s Logic provides an AI-powered receptionist platform that answers phone
              calls, responds to SMS messages, books appointments, and manages leads on behalf
              of small businesses. The service is available at{" "}
              <a href="https://app.solomonslogic.com" className="text-blue-400 underline">app.solomonslogic.com</a>.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">3. Subscriptions & Billing</h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>Subscriptions are billed monthly via Stripe</li>
              <li>Plans start at $149/month (Starter), $199/month (Professional), and $599/month (Growth)</li>
              <li>You may cancel at any time; cancellation takes effect at the end of your billing period</li>
              <li>No refunds are issued for partial months</li>
              <li>Consent to purchase is not a condition of receiving SMS messages</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">4. SMS Communications</h2>
            <p>
              By providing a phone number and signing up, you consent to receive SMS messages
              related to your account, including appointment reminders, lead notifications,
              and service updates. Message frequency varies. Message and data rates may apply.
            </p>
            <p className="mt-2">
              To opt out of SMS messages at any time, reply <strong>STOP</strong> to any message.
              Reply <strong>HELP</strong> for support. For more information, contact{" "}
              <a href="mailto:solomonslogic@gmail.com" className="text-blue-400 underline">solomonslogic@gmail.com</a>.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Send spam or unsolicited messages to contacts who have not opted in</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Impersonate any person or entity</li>
              <li>Interfere with the Service or its infrastructure</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">6. AI-Generated Content</h2>
            <p>
              Responses generated by our AI are automated and may not always be perfectly
              accurate. You are responsible for reviewing AI-generated content before relying
              on it for business decisions. Solomon&apos;s Logic is not liable for errors in
              AI-generated responses.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">7. Limitation of Liability</h2>
            <p>
              Solomon&apos;s Logic shall not be liable for any indirect, incidental, or consequential
              damages arising from your use of the Service. Our total liability to you shall
              not exceed the amount you paid in the previous 30 days.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">8. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account if you violate these
              Terms. You may cancel your account at any time from your dashboard settings.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">9. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after
              changes constitutes acceptance of the new Terms.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-white mb-2">10. Contact</h2>
            <p>
              Solomon&apos;s Logic<br />
              Email: <a href="mailto:solomonslogic@gmail.com" className="text-blue-400 underline">solomonslogic@gmail.com</a><br />
              Website: <a href="https://app.solomonslogic.com" className="text-blue-400 underline">app.solomonslogic.com</a>
            </p>
          </div>
        </section>
      </div>
    </main>
  );
}
